### ISSUE TITLE
Improve the usage of external toolchain

### ISSUE THREAD

**Issue by jserv** [olibc/build#2]
At present, external toolchain support is very constraint:
- full path is required
- no explicit `make` integration (only `BUILD.sh` is supported)
- no sanity check for toolchain

**Comment by kito-cheng** [comment]
How about enable -Wl,--icf=safe if detected the linker is gold?

**Comment by jserv** [comment]
@kito-cheng It sound reasonable.

**Comment by kito-cheng** [comment]
Automatically detect linker now
https://github.com/olibc/build/commit/d658e9b15fd39bfde5e75020b37e720a308b8aea
https://github.com/olibc/olibc/commit/6fcd6128aa78f1f77da9045f3fd2f1171eb67798

**Comment by jserv** [comment]
These requests should be already implemented.
