### ISSUE TITLE
Set up Travis CI as hosted continuous integration

### ISSUE THREAD

**Issue by jserv** [olibc/build#4]
Since olibc supports various targets and feature configurations, it is important to utilize continuous integration to ensure the validation of target/feature completeness at least.

Reference:
- http://about.travis-ci.org/docs/user/getting-started/

**Comment by kito-cheng** [comment]
https://github.com/olibc/olibc/commit/a5e04643b27079ca6d44b81adbe03f493654db02

Only trigger when olibc push now, I don't find multi-git repo trigger :P...

URL : https://travis-ci.org/olibc/olibc

**Comment by kito-cheng** [comment]
Note:
Just add config file to travis-ci/configs/ for more build test
